services:
  - type: web
    name: tienda-camisetas
    runtime: python
    buildCommand: pip install -r requirements_tienda.txt
    startCommand: python main.py
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
    healthCheckPath: /admin/login
